themes_homepage:
    path:     /
    defaults: { _controller: ThemesBundle:Default:index }
themes_changebg:
    path:     /ChangeBackground
    defaults: { _controller: ThemesBundle:Default:changebg }
themes_changetheme:
    path:     /ChangeTheme
    defaults: { _controller: ThemesBundle:Default:changetheme }

